replicaCount: 1

image:
  repository: docker.io/helmapp

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: harthi.com
      paths:
        - path: /
          pathType: Prefix
        - path: /a
          pathType: Prefix
        - path: /b
          pathType: Prefix